### ISSUE TITLE
Write Developer Docs and README

### ISSUE THREAD

**Issue by Raghunath-Kunigiri** [austin-carnahan/software-engineering-24#2]
User Story: Write Developer Documentation and README
Assignee: Raghunath Kunigiri

Due Date: 2024-07-01

Title: Write Developer Documentation and README

Description:
As a developer, I would like to have comprehensive developer documentation and a README file for our project. This will ensure that all team members and future contributors have a clear understanding of the project's structure, setup, and development practices, facilitating smooth collaboration and efficient development.

Acceptance Criteria:

A README file that includes:
Project title
Project description
Initial setup instructions
Project structure
Tools and libraries used
Contributor information
Additional information or references to further documentation
Developer documentation that includes:
Instructions for setting up the development environment
Detailed project structure and files explanation
Instructions for running the application
Guidelines for managing dependencies
Contributing guidelines

**Comment by Raghunath9493** [comment]
README

**Comment by Raghunath9493** [comment]
README

**Comment by Raghunath9493** [comment]
User Story

**Comment by austin-carnahan** [comment]
Added directly to main branch
